### PR TITLE
Update documentation and include USB configuration files

### PR DESCRIPTION
**Pull request by blackketter**
I pulled the documentation from the web site and included it here, along with the USB configuration files to have everything in one place.

Specifically, I'd like to see platformio and other build systems include the USB configuration files so that users don't need to search around to find the right configurations.

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
I'm going to merge this now, but I want to remove the rules file and link to the copy on the website.  Occasionally the rules file has needed updates at we add other features or as Linux distros change.  Experience has shows 2 copies always end up having one of them get out of date, so for the udev rules there really needs to be only a single official version.

**Comment by blackketter** [comment]
Thanks, Paul.  Any reason not to have GitHub host the authoritative version?

**Comment by blackketter** [comment]
To elaborate, it would be great if third-parties can pull from GitHub to build installers and the like.  For example, to get platformio to work on the RasPi, one has to dig around to find the UDEV file.

**Comment by PaulStoffregen** [comment]
Someday I'll probably use github as the source for all the website files.  Restructuring how we do things will be, and already has been for some time, a gradual process.

But for now, and at least the next several months, probably next year, there's a ton of stuff planned.  Definitely not looking to substantially reorganize stuff while still working on the K66-based board.

**Pull request merged**
